import { 
  ShonenMoveInfo, 
  ShonenPowerType, 
  PlayerSkinItem, 
  GhostSkinItem, 
  MazeSkinItem, 
  BonusItem,
  DailyMission
} from './types';

export const GRID_WIDTH = 21;
export const GRID_HEIGHT = 23;
export const BASE_TILE_SIZE = 24;
export const TOTAL_LEVELS = 1001;

// 36 Exhaustive Shonen Power-Ups with Rich Lore, Ki Costs & Effects
export const SHONEN_MOVES: Record<ShonenPowerType, ShonenMoveInfo> = {
  SUPER_SAIYAN: {
    id: 'SUPER_SAIYAN',
    name: 'Super Saiyan Awakening',
    japaneseName: '超サイヤ人覚醒',
    animeSource: 'Dragon Ball Z',
    description: 'Surge with golden Ki aura. Yokai ghosts flee in terror and can be eaten for exponential combo scores!',
    kiCost: 25,
    cooldown: 8,
    duration: 10,
    icon: '⚡',
    color: '#FACC15',
    rarity: 'COMMON',
    soundKey: 'super_saiyan',
    hotkey: 'Space',
  },
  KAMEHAMEHA: {
    id: 'KAMEHAMEHA',
    name: 'Kamehameha Wave',
    japaneseName: 'かめはめ波',
    animeSource: 'Dragon Ball',
    description: 'Charge and fire a colossal azure Ki beam that vaporizes every ghost and consumes all dots in its path!',
    kiCost: 40,
    cooldown: 12,
    duration: 2.2,
    icon: '🌊',
    color: '#06B6D4',
    rarity: 'COMMON',
    soundKey: 'kamehameha',
    hotkey: 'J / Pad X',
  },
  DOMAIN_EXPANSION: {
    id: 'DOMAIN_EXPANSION',
    name: 'Domain: Infinite Void',
    japaneseName: '領域展開・無量空処',
    animeSource: 'Jujutsu Kaisen',
    description: 'Cast a supreme dimensional domain. Time completely freezes for all ghosts while granting you hyper speed!',
    kiCost: 50,
    cooldown: 16,
    duration: 6.5,
    icon: '🌌',
    color: '#8B5CF6',
    rarity: 'EPIC',
    soundKey: 'domain_expansion',
    hotkey: 'K / Pad Y',
  },
  BANKAI_SLASH: {
    id: 'BANKAI_SLASH',
    name: 'Bankai: Getsuga Flash',
    japaneseName: '卍解・月牙天衝',
    animeSource: 'Bleach',
    description: 'Execute Shunpo flash step through maze walls, instantly slicing all nearby Yokai with celestial blade strikes!',
    kiCost: 35,
    cooldown: 10,
    duration: 1.5,
    icon: '⚔️',
    color: '#EF4444',
    rarity: 'RARE',
    soundKey: 'bankai',
    hotkey: 'L / Pad B',
  },
  RASENGAN_VACUUM: {
    id: 'RASENGAN_VACUUM',
    name: 'Rasengan: Chakra Vortex',
    japaneseName: '螺旋丸・渦巻',
    animeSource: 'Naruto Shippuden',
    description: 'Conjure a high-density swirling chakra vortex that pulls all surrounding spirit dots into your core!',
    kiCost: 30,
    cooldown: 9,
    duration: 7,
    icon: '🌀',
    color: '#3B82F6',
    rarity: 'COMMON',
    soundKey: 'rasengan',
    hotkey: 'U / Pad LB',
  },
  GEAR_5_BOUNCE: {
    id: 'GEAR_5_BOUNCE',
    name: 'Gear 5: Sun God Joy',
    japaneseName: 'ギア５・太陽の神',
    animeSource: 'One Piece',
    description: 'Transform into the warrior of liberation! Cartoon invincibility where ghosts bounce away comically on touch!',
    kiCost: 60,
    cooldown: 20,
    duration: 8,
    icon: '☀️',
    color: '#EC4899',
    rarity: 'LEGENDARY',
    soundKey: 'gear_5',
    hotkey: 'I / Pad RB',
  },
  AMATERASU_FLAME: {
    id: 'AMATERASU_FLAME',
    name: 'Amaterasu: Black Flames',
    japaneseName: '天照・黒炎',
    animeSource: 'Naruto',
    description: 'Ignite never-ending black flames that incinerate all spirit dots in a 4-tile radial blast and burn ghosts.',
    kiCost: 45,
    cooldown: 14,
    duration: 4,
    icon: '🔥',
    color: '#18181B',
    rarity: 'EPIC',
    soundKey: 'bankai',
  },
  STAR_PLATINUM_TIME: {
    id: 'STAR_PLATINUM_TIME',
    name: 'Star Platinum: The World',
    japaneseName: 'スタープラチナ・ザ・ワールド',
    animeSource: 'JoJo Bizarre Adventure',
    description: 'Time grinds to an absolute halt for 4.5 seconds. Freely navigate the maze while enemies are frozen in place!',
    kiCost: 55,
    cooldown: 18,
    duration: 4.5,
    icon: '⏳',
    color: '#F59E0B',
    rarity: 'LEGENDARY',
    soundKey: 'domain_expansion',
  },
  DETROIT_SMASH: {
    id: 'DETROIT_SMASH',
    name: 'Detroit Smash: Air Blast',
    japaneseName: 'デトロイトスマッシュ',
    animeSource: 'My Hero Academia',
    description: '100% One For All punch creating a hurricane shockwave that clears entire rows of dots and knocks back Yokai.',
    kiCost: 35,
    cooldown: 11,
    duration: 1.8,
    icon: '💥',
    color: '#10B981',
    rarity: 'RARE',
    soundKey: 'kamehameha',
  },
  SPIRIT_GUN: {
    id: 'SPIRIT_GUN',
    name: 'Reigan: Spirit Gun',
    japaneseName: '霊丸・レイガン',
    animeSource: 'Yu Yu Hakusho',
    description: 'Fires high-velocity spirit energy bullet piercing clean through multiple ghosts in your path.',
    kiCost: 30,
    cooldown: 8,
    duration: 1.5,
    icon: '👉',
    color: '#38BDF8',
    rarity: 'COMMON',
    soundKey: 'kamehameha',
  },
  SERIOUS_PUNCH: {
    id: 'SERIOUS_PUNCH',
    name: 'Serious Series: Serious Punch',
    japaneseName: '必殺マジシリーズ・マジ殴り',
    animeSource: 'One Punch Man',
    description: 'Unleashes atmospheric shockwave destroying all ghosts currently active on the screen in a single blast!',
    kiCost: 75,
    cooldown: 25,
    duration: 2.5,
    icon: '🥊',
    color: '#DC2626',
    rarity: 'MYTHIC',
    soundKey: 'kamehameha',
  },
  WATER_BREATHING_DRAGON: {
    id: 'WATER_BREATHING_DRAGON',
    name: 'Water Breathing: Tenth Form',
    japaneseName: '水の呼吸・拾ノ型 生生流転',
    animeSource: 'Demon Slayer',
    description: 'Summons a flowing azure water dragon that surges through the maze corridors collecting spirit dots along its trail.',
    kiCost: 40,
    cooldown: 12,
    duration: 5,
    icon: '🐉',
    color: '#0284C7',
    rarity: 'RARE',
    soundKey: 'rasengan',
  },
  UNLIMITED_BLADES: {
    id: 'UNLIMITED_BLADES',
    name: 'Unlimited Blade Works',
    japaneseName: '無限の剣製',
    animeSource: 'Fate/stay night',
    description: 'Manifests a reality marble where infinite phantasm blades rain from the sky, striking every ghost.',
    kiCost: 55,
    cooldown: 15,
    duration: 4,
    icon: '🗡️',
    color: '#D97706',
    rarity: 'EPIC',
    soundKey: 'bankai',
  },
  DEATH_NOTE_MARK: {
    id: 'DEATH_NOTE_MARK',
    name: 'Shinigami Heart Failure',
    japaneseName: '死神のノート',
    animeSource: 'Death Note',
    description: 'Writes the true name of the most threatening ghost into the notebook, eliminating it instantly.',
    kiCost: 30,
    cooldown: 10,
    duration: 1,
    icon: '📓',
    color: '#475569',
    rarity: 'RARE',
    soundKey: 'domain_expansion',
  },
  GUM_GUM_GATLING: {
    id: 'GUM_GUM_GATLING',
    name: 'Gum-Gum Jet Gatling',
    japaneseName: 'ゴムゴムのJET銃乱打',
    animeSource: 'One Piece',
    description: 'Fires high-speed rubber punch barrage in your direction, eating ghosts without requiring power orbs.',
    kiCost: 35,
    cooldown: 9,
    duration: 3.5,
    icon: '👊',
    color: '#EA580C',
    rarity: 'COMMON',
    soundKey: 'gear_5',
  },
  SHADOW_CLONE_JUTSU: {
    id: 'SHADOW_CLONE_JUTSU',
    name: 'Multi-Shadow Clone Jutsu',
    japaneseName: '多重影分身の術',
    animeSource: 'Naruto',
    description: 'Spawns 2 mini shadow clone Pac-Men that dash through corridors gathering spirit dots for you!',
    kiCost: 45,
    cooldown: 14,
    duration: 7,
    icon: '👥',
    color: '#F97316',
    rarity: 'RARE',
    soundKey: 'rasengan',
  },
  FULL_COWL_DASH: {
    id: 'FULL_COWL_DASH',
    name: 'Full Cowl: Shoot Style',
    japaneseName: 'ワン・フォー・オール フルカウル',
    animeSource: 'My Hero Academia',
    description: 'Green lightning surges through your body granting +100% movement speed and acrobatic bounce!',
    kiCost: 30,
    cooldown: 8,
    duration: 6,
    icon: '⚡',
    color: '#22C55E',
    rarity: 'COMMON',
    soundKey: 'super_saiyan',
  },
  DRAGON_ROAR_BREATH: {
    id: 'DRAGON_ROAR_BREATH',
    name: 'Fire Dragon Roar',
    japaneseName: '火竜の咆哮',
    animeSource: 'Fairy Tail',
    description: 'Exhales a wide cone of fiery dragon breath that dissolves dots into bonus points and repels ghosts.',
    kiCost: 35,
    cooldown: 10,
    duration: 2.5,
    icon: '🔥',
    color: '#EF4444',
    rarity: 'COMMON',
    soundKey: 'kamehameha',
  },
  CHIDORI_LIGHTNING: {
    id: 'CHIDORI_LIGHTNING',
    name: 'Chidori: One Thousand Birds',
    japaneseName: '千鳥・雷切',
    animeSource: 'Naruto',
    description: 'Electrifies the corridor behind you with high-voltage lightning traps that paralyze and destroy ghosts.',
    kiCost: 40,
    cooldown: 11,
    duration: 5,
    icon: '⚡',
    color: '#38BDF8',
    rarity: 'RARE',
    soundKey: 'super_saiyan',
  },
  ALCHEMIST_TRANSMUTE: {
    id: 'ALCHEMIST_TRANSMUTE',
    name: 'Alchemical Transmutation',
    japaneseName: '錬金術・等価交換',
    animeSource: 'Fullmetal Alchemist',
    description: 'Claps hands to transmute 8 nearby maze wall blocks directly into high-value Golden Spirit Orbs!',
    kiCost: 40,
    cooldown: 13,
    duration: 2,
    icon: '✨',
    color: '#EAB308',
    rarity: 'EPIC',
    soundKey: 'bonus_item',
  },
  GIGA_DRILL_BREAK: {
    id: 'GIGA_DRILL_BREAK',
    name: 'Giga Drill Break',
    japaneseName: 'ギガドリルブレイク',
    animeSource: 'Gurren Lagann',
    description: 'Spiral energy generates a massive drill that pierces straight through inner maze walls, creating new shortcuts!',
    kiCost: 50,
    cooldown: 15,
    duration: 3,
    icon: '🌀',
    color: '#06B6D4',
    rarity: 'EPIC',
    soundKey: 'bankai',
  },
  SPIRIT_BOMB: {
    id: 'SPIRIT_BOMB',
    name: 'Genki Dama: Spirit Bomb',
    japaneseName: '元気玉',
    animeSource: 'Dragon Ball Z',
    description: 'Gathers spirit energy from the cosmos into a giant luminous orb that sweeps across the arena absorbing everything.',
    kiCost: 70,
    cooldown: 24,
    duration: 4.5,
    icon: '🌐',
    color: '#60A5FA',
    rarity: 'LEGENDARY',
    soundKey: 'kamehameha',
  },
  TITAN_ROAR_FEAR: {
    id: 'TITAN_ROAR_FEAR',
    name: 'Attack Titan: Coordinate Roar',
    japaneseName: '進撃の巨人・咆哮',
    animeSource: 'Attack on Titan',
    description: 'A terrifying primordial roar stuns all ghosts in deep fear for 5 seconds and strips their speed.',
    kiCost: 35,
    cooldown: 10,
    duration: 5,
    icon: '👹',
    color: '#991B1B',
    rarity: 'RARE',
    soundKey: 'gameOver',
  },
  HOLLOW_MASK_RAGE: {
    id: 'HOLLOW_MASK_RAGE',
    name: 'Hollowfication Mask Rage',
    japaneseName: '虚化・ホロウの力',
    animeSource: 'Bleach',
    description: 'Don the black-and-red Hollow Mask! Increases speed by 60% and grants a triple 3x combo score multiplier!',
    kiCost: 45,
    cooldown: 12,
    duration: 7,
    icon: '🎭',
    color: '#E11D48',
    rarity: 'EPIC',
    soundKey: 'bankai',
  },
  ULTRA_INSTINCT: {
    id: 'ULTRA_INSTINCT',
    name: 'Ultra Instinct Sign',
    japaneseName: '身勝手の極意',
    animeSource: 'Dragon Ball Super',
    description: 'Silver divine aura. The body moves on pure instinct, effortlessly auto-dodging any lethal ghost contact for 5s!',
    kiCost: 65,
    cooldown: 22,
    duration: 5.5,
    icon: '🌌',
    color: '#E2E8F0',
    rarity: 'MYTHIC',
    soundKey: 'domain_expansion',
  },
  CONQUERORS_HAKI: {
    id: 'CONQUERORS_HAKI',
    name: "Conqueror's Supreme Haki",
    japaneseName: '覇王色の覇気',
    animeSource: 'One Piece',
    description: 'Release supreme kingly will! Knocks out all active Yokai ghosts instantly, sending their spirits back to the ghost pen.',
    kiCost: 60,
    cooldown: 18,
    duration: 2,
    icon: '👑',
    color: '#4C1D95',
    rarity: 'LEGENDARY',
    soundKey: 'domain_expansion',
  },
  TSUKUYOMI_ILLUSION: {
    id: 'TSUKUYOMI_ILLUSION',
    name: 'Tsukuyomi: Infinite Nightmare',
    japaneseName: '月読・幻術',
    animeSource: 'Naruto',
    description: 'Traps the ghosts inside an optical illusion matrix, inverting their AI controls and making them spin in loops.',
    kiCost: 40,
    cooldown: 11,
    duration: 6,
    icon: '👁️',
    color: '#BE123C',
    rarity: 'RARE',
    soundKey: 'domain_expansion',
  },
  ICE_AGE_FREEZE: {
    id: 'ICE_AGE_FREEZE',
    name: 'Ice Age: Absolute Zero',
    japaneseName: 'アイスエイジ・氷河時代',
    animeSource: 'One Piece',
    description: 'Flash-freezes the entire maze surface in gleaming frost crystals, shattering ghosts if bumped into!',
    kiCost: 50,
    cooldown: 15,
    duration: 5,
    icon: '❄️',
    color: '#A5F3FC',
    rarity: 'EPIC',
    soundKey: 'domain_expansion',
  },
  FINAL_FLASH: {
    id: 'FINAL_FLASH',
    name: 'Vegeta Final Flash',
    japaneseName: 'ファイナルフラッシュ',
    animeSource: 'Dragon Ball Z',
    description: 'Condenses all pride and power into an ultra-wide yellow energy beam that vaporizes a 3-tile wide corridor!',
    kiCost: 55,
    cooldown: 16,
    duration: 2.5,
    icon: '⚡',
    color: '#FDE047',
    rarity: 'EPIC',
    soundKey: 'kamehameha',
  },
  SHADOW_MONARCH_ARISE: {
    id: 'SHADOW_MONARCH_ARISE',
    name: 'Shadow Extraction: Arise',
    japaneseName: '起きろ・影の抽出',
    animeSource: 'Solo Leveling',
    description: 'Extracted shadows of eaten ghosts rise as glowing purple shadow soldiers that vacuum dots for your glory.',
    kiCost: 60,
    cooldown: 19,
    duration: 8,
    icon: '👤',
    color: '#7C3AED',
    rarity: 'MYTHIC',
    soundKey: 'domain_expansion',
  },
  ROOM_SHAMBLES: {
    id: 'ROOM_SHAMBLES',
    name: 'Op-Op Fruit: Room Shambles',
    japaneseName: 'ROOM・シャンブルズ',
    animeSource: 'One Piece',
    description: 'Deploys a surgical dome and instantly swaps player coordinates with the furthest ghost in the maze.',
    kiCost: 30,
    cooldown: 8,
    duration: 1,
    icon: '💙',
    color: '#0284C7',
    rarity: 'RARE',
    soundKey: 'rasengan',
  },
  SOLAR_FLARE_BLIND: {
    id: 'SOLAR_FLARE_BLIND',
    name: 'Taiyoken: Solar Flare',
    japaneseName: '太陽拳',
    animeSource: 'Dragon Ball',
    description: 'Emits a blinding burst of pure solar light, blinding all ghosts and causing them to wander aimlessly.',
    kiCost: 25,
    cooldown: 7,
    duration: 4.5,
    icon: '☀️',
    color: '#FEF08A',
    rarity: 'COMMON',
    soundKey: 'powerOrb',
  },
  HEAVENLY_RESTRICTION: {
    id: 'HEAVENLY_RESTRICTION',
    name: 'Heavenly Restriction: Physical Apex',
    japaneseName: '天与呪縛・肉体の極致',
    animeSource: 'Jujutsu Kaisen',
    description: 'Zero cursed energy allows transcendent physical speed and the ability to stomp ghosts on collision!',
    kiCost: 35,
    cooldown: 10,
    duration: 6,
    icon: '🥋',
    color: '#64748B',
    rarity: 'EPIC',
    soundKey: 'bankai',
  },
  SUPER_TENGEN_TOPPA: {
    id: 'SUPER_TENGEN_TOPPA',
    name: 'Super Galaxy Cosmos',
    japaneseName: '超銀河グレンラガン',
    animeSource: 'Gurren Lagann',
    description: 'Cosmic size expansion! Pac-Man grows into a massive galactic avatar engulfing entire intersections.',
    kiCost: 75,
    cooldown: 25,
    duration: 6,
    icon: '🌌',
    color: '#C084FC',
    rarity: 'MYTHIC',
    soundKey: 'gear_5',
  },
  NINE_TAILS_CLOAK: {
    id: 'NINE_TAILS_CLOAK',
    name: 'Kurama Nine-Tails Chakra Cloak',
    japaneseName: '九尾のチャクラ衣',
    animeSource: 'Naruto',
    description: 'Nine blazing chakra tails sweep all surrounding corridors, eating dots and deflecting ghost attacks.',
    kiCost: 50,
    cooldown: 14,
    duration: 6.5,
    icon: '🦊',
    color: '#FB923C',
    rarity: 'LEGENDARY',
    soundKey: 'super_saiyan',
  },
  THUNDER_CLAP_FLASH: {
    id: 'THUNDER_CLAP_FLASH',
    name: 'Thunder Breathing: First Form',
    japaneseName: '雷の呼吸・壱ノ型 霹靂一閃',
    animeSource: 'Demon Slayer',
    description: 'Godspeed lightning strike! Teleports instantly 6 tiles ahead and destroys every ghost along the trajectory.',
    kiCost: 40,
    cooldown: 9,
    duration: 1.2,
    icon: '⚡',
    color: '#FACC15',
    rarity: 'RARE',
    soundKey: 'bankai',
  },
};

// 12 Collectible Anime Pac-Man Character Skins
export const GACHA_PAC_SKINS: PlayerSkinItem[] = [
  {
    id: 'skin-classic-neon',
    name: 'Classic Neon Shinobi',
    animeSource: 'Arcade Prime',
    color: '#FACC15',
    auraColor: '#FDE047',
    headgear: 'headband',
    rarity: 'COMMON',
    previewIcon: '🟡',
  },
  {
    id: 'skin-super-saiyan',
    name: 'Saiyan Warrior Pac',
    animeSource: 'Dragon Ball Z',
    color: '#FBBF24',
    auraColor: '#FEF08A',
    headgear: 'super_hair',
    rarity: 'RARE',
    previewIcon: '👱‍♂️',
  },
  {
    id: 'skin-straw-hat',
    name: 'Pirate King Joy Pac',
    animeSource: 'One Piece',
    color: '#FB7185',
    auraColor: '#FDA4AF',
    headgear: 'straw_hat',
    rarity: 'RARE',
    previewIcon: '👒',
  },
  {
    id: 'skin-hollow-ichigo',
    name: 'Hollow Mask Reaper',
    animeSource: 'Bleach',
    color: '#E11D48',
    auraColor: '#18181B',
    headgear: 'hollow_mask',
    rarity: 'EPIC',
    previewIcon: '🎭',
  },
  {
    id: 'skin-blindfold-gojo',
    name: 'Limitless Sorcerer',
    animeSource: 'Jujutsu Kaisen',
    color: '#818CF8',
    auraColor: '#C084FC',
    headgear: 'blindfold',
    rarity: 'LEGENDARY',
    previewIcon: '🕶️',
  },
  {
    id: 'skin-demon-tanjiro',
    name: 'Sun Breathing Slayer',
    animeSource: 'Demon Slayer',
    color: '#059669',
    auraColor: '#34D399',
    headgear: 'tanjiro_earrings',
    rarity: 'RARE',
    previewIcon: '🗡️',
  },
  {
    id: 'skin-shadow-jinwoo',
    name: 'Shadow Monarch Jinwoo',
    animeSource: 'Solo Leveling',
    color: '#6D28D9',
    auraColor: '#A78BFA',
    headgear: 'monarch_shadow',
    rarity: 'MYTHIC',
    previewIcon: '👑',
  },
  {
    id: 'skin-sun-god-joyboy',
    name: 'Warrior of Liberation (Nika)',
    animeSource: 'One Piece',
    color: '#FFFFFF',
    auraColor: '#F472B6',
    headgear: 'flame_crown',
    rarity: 'MYTHIC',
    previewIcon: '☀️',
  },
  {
    id: 'skin-attack-titan',
    name: 'Founding Shifter Pac',
    animeSource: 'Attack on Titan',
    color: '#B91C1C',
    auraColor: '#F87171',
    headgear: 'titan_eyes',
    rarity: 'EPIC',
    previewIcon: '👹',
  },
  {
    id: 'skin-cyber-ninja',
    name: 'Akihabara Cyber Ninja',
    animeSource: 'Cyberpunk Edgerunners',
    color: '#06B6D4',
    auraColor: '#22D3EE',
    headgear: 'headband',
    rarity: 'RARE',
    previewIcon: '🤖',
  },
  {
    id: 'skin-golden-frieza',
    name: 'Emperor Golden Pac',
    animeSource: 'Dragon Ball Super',
    color: '#CA8A04',
    auraColor: '#9333EA',
    headgear: 'none',
    rarity: 'EPIC',
    previewIcon: '🥇',
  },
  {
    id: 'skin-nine-tails-naruto',
    name: 'Sage of Six Paths',
    animeSource: 'Naruto',
    color: '#EA580C',
    auraColor: '#FDBA74',
    headgear: 'flame_crown',
    rarity: 'LEGENDARY',
    previewIcon: '🦊',
  },
];

// Collectible Ghost Skins
export const GACHA_GHOST_SKINS: GhostSkinItem[] = [
  {
    id: 'ghost-classic-oni',
    name: 'Classic Neo Oni Yokai',
    animeSource: 'Arcade Prime',
    akumaColor: '#EF4444',
    kitsuneColor: '#F472B6',
    raidenColor: '#06B6D4',
    kageColor: '#F97316',
    pattern: 'standard',
    rarity: 'COMMON',
    previewIcon: '👻',
  },
  {
    id: 'ghost-akatsuki',
    name: 'Akatsuki Renegade Spirits',
    animeSource: 'Naruto',
    akumaColor: '#991B1B',
    kitsuneColor: '#BE123C',
    raidenColor: '#1E293B',
    kageColor: '#0F172A',
    pattern: 'akatsuki_clouds',
    rarity: 'EPIC',
    previewIcon: '☁️',
  },
  {
    id: 'ghost-espada-hollows',
    name: 'Hueco Mundo Espada Hollows',
    animeSource: 'Bleach',
    akumaColor: '#F8FAFC',
    kitsuneColor: '#E2E8F0',
    raidenColor: '#CBD5E1',
    kageColor: '#94A3B8',
    pattern: 'espada_white',
    rarity: 'RARE',
    previewIcon: '💀',
  },
  {
    id: 'ghost-demon-upper-moons',
    name: 'Twelve Kizuki Upper Moons',
    animeSource: 'Demon Slayer',
    akumaColor: '#7F1D1D',
    kitsuneColor: '#831843',
    raidenColor: '#1E1B4B',
    kageColor: '#312E81',
    pattern: 'demon_slayer_haori',
    rarity: 'LEGENDARY',
    previewIcon: '🌙',
  },
  {
    id: 'ghost-cyber-mecha',
    name: 'Neo-Tokyo Cyber Drones',
    animeSource: 'Cyberpunk',
    akumaColor: '#FF0055',
    kitsuneColor: '#00F0FF',
    raidenColor: '#FFE600',
    kageColor: '#B000FF',
    pattern: 'cyber_mecha',
    rarity: 'RARE',
    previewIcon: '👾',
  },
  {
    id: 'ghost-shinigami-death',
    name: 'Soul Society Shinigami',
    animeSource: 'Bleach',
    akumaColor: '#000000',
    kitsuneColor: '#18181B',
    raidenColor: '#27272A',
    kageColor: '#3F3F46',
    pattern: 'shinigami_robes',
    rarity: 'EPIC',
    previewIcon: '⚔️',
  },
];

// Collectible Maze Textures & Architectural Styles
export const GACHA_MAZE_SKINS: MazeSkinItem[] = [
  {
    id: 'maze-neon-cyber',
    name: 'Neo-Tokyo Laser Grid',
    style: 'NEON_GLOW',
    primaryColor: '#00f0ff',
    secondaryColor: '#ff0077',
    glowColor: 'rgba(0, 240, 255, 0.7)',
    dotColor: '#fdfa72',
    rarity: 'COMMON',
  },
  {
    id: 'maze-ukiyoe-woodblock',
    name: 'Edo Ukiyo-e Woodblock',
    style: 'WOODBLOCK_UKIYOE',
    primaryColor: '#1e3a8a',
    secondaryColor: '#b45309',
    glowColor: 'rgba(30, 58, 138, 0.7)',
    dotColor: '#fef08a',
    rarity: 'RARE',
  },
  {
    id: 'maze-gold-leaf',
    name: 'Kyoto Golden Shrine',
    style: 'GOLD_LEAF_SHRINE',
    primaryColor: '#d97706',
    secondaryColor: '#f59e0b',
    glowColor: 'rgba(217, 119, 6, 0.7)',
    dotColor: '#ffffff',
    rarity: 'EPIC',
  },
  {
    id: 'maze-obsidian-crystal',
    name: 'Obsidian Void Crystal',
    style: 'OBSIDIAN_CRYSTAL',
    primaryColor: '#8b5cf6',
    secondaryColor: '#ec4899',
    glowColor: 'rgba(139, 92, 246, 0.8)',
    dotColor: '#38bdf8',
    rarity: 'EPIC',
  },
  {
    id: 'maze-magma-inferno',
    name: 'Volcanic Dragon Core',
    style: 'MAGMA_INFERNO',
    primaryColor: '#ea580c',
    secondaryColor: '#dc2626',
    glowColor: 'rgba(234, 88, 12, 0.8)',
    dotColor: '#fed7aa',
    rarity: 'RARE',
  },
  {
    id: 'maze-sakura-parchment',
    name: 'Cherry Blossom Parchment',
    style: 'SAKURA_PARCHMENT',
    primaryColor: '#f43f5e',
    secondaryColor: '#fb7185',
    glowColor: 'rgba(244, 63, 94, 0.7)',
    dotColor: '#fecdd3',
    rarity: 'RARE',
  },
  {
    id: 'maze-carbon-fiber',
    name: 'Mecha Carbon Matrix',
    style: 'CARBON_FIBER',
    primaryColor: '#10b981',
    secondaryColor: '#06b6d4',
    glowColor: 'rgba(16, 185, 129, 0.7)',
    dotColor: '#a7f3d0',
    rarity: 'LEGENDARY',
  },
];

// Daily Missions Generation Template
export function generateDailyMissions(dateKey: string): DailyMission[] {
  return [
    {
      id: `mission-dots-${dateKey}`,
      title: 'Spirit Hunger',
      description: 'Eat 60 spirit pellets in a single stage without losing a life.',
      category: 'DOTS',
      targetCount: 60,
      currentProgress: 0,
      rewardCoins: 150,
      rewardKiBoost: 10,
      completed: false,
      claimed: false,
    },
    {
      id: `mission-ghosts-${dateKey}`,
      title: 'Yokai Exorcist',
      description: 'Vaporize or eat 6 Yokai ghosts using Shonen Special Moves.',
      category: 'GHOSTS',
      targetCount: 6,
      currentProgress: 0,
      rewardCoins: 200,
      rewardMultiplierBoost: 1,
      completed: false,
      claimed: false,
    },
    {
      id: `mission-powers-${dateKey}`,
      title: 'Chakra Mastery',
      description: 'Unleash 4 different Shonen Special Moves in battle.',
      category: 'POWERS',
      targetCount: 4,
      currentProgress: 0,
      rewardCoins: 175,
      completed: false,
      claimed: false,
    },
    {
      id: `mission-difficulty-${dateKey}`,
      title: 'Hardcore Shinobi',
      description: 'Clear any stage on Hard, Ghostly, or Hunter difficulty.',
      category: 'DIFFICULTY',
      targetCount: 1,
      currentProgress: 0,
      rewardCoins: 300,
      rewardKiBoost: 15,
      completed: false,
      claimed: false,
    },
    {
      id: `mission-score-${dateKey}`,
      title: 'Arcade Legend',
      description: 'Accumulate a score of at least 12,000 points.',
      category: 'SCORE',
      targetCount: 12000,
      currentProgress: 0,
      rewardCoins: 250,
      rewardMultiplierBoost: 1,
      completed: false,
      claimed: false,
    },
  ];
}

export const ANIME_BONUS_ITEMS: Omit<BonusItem, 'x' | 'y' | 'gridX' | 'gridY' | 'duration' | 'active'>[] = [
  { name: 'Ichiraku Ramen', japanese: '一楽ラーメン', icon: '🍜', points: 100 },
  { name: 'Senzu Bean', japanese: '仙豆', icon: '🫘', points: 300 },
  { name: 'Chakra Pill', japanese: 'チャクラの丸薬', icon: '💊', points: 500 },
  { name: 'Ninja Kunai', japanese: 'クナイ', icon: '🗡️', points: 700 },
  { name: 'Straw Hat Treasure', japanese: '麦わら帽子', icon: '👒', points: 1000 },
  { name: 'Flame Devil Fruit', japanese: 'メラメラの実', icon: '🍈', points: 2000 },
  { name: 'Dragon Star Orb', japanese: 'ドラゴンボール', icon: '🔮', points: 5000 },
];
